### ISSUE TITLE
Purity

### ISSUE THREAD

**Issue by yeyeye529** [harvardnlp/neural-template-gen#10]
Thank you for sharing your excellent code!
I have some questions on the calculation of Purity metrics shown in Table 5 in the EMNLP'18 paper.
I could not find the part of purity in this code. When I try to implement by myself, I'm not sure about some details.
Could you please push the code of calculating purity?
Thank you!

**Comment by swiseman** [comment]
Sorry for the delay; it should now be possible to calculate purity using the '-align' argument in chsmm.py, and the code should reproduce the purity numbers in the (updated) paper.
