### ISSUE TITLE
question about dataset

### ISSUE THREAD

**Issue by M5218** [harvardnlp/neural-template-gen#12]
Thank you for sharing your excellent code!
In make_e2e_labedata.py
e2e_train_src = "trainset-source.tok"
e2e_train_tgt = "trainset-target.tok"
e2e_val_src = "devset-source.tok"
e2e_val_tgt = "devset-target.tok"

I have not found these files, what do these files mean?
Thank you!

**Comment by swiseman** [comment]
Those correspond to src_train.txt, the gold target generations for src_train.txt, src_valid.txt, and the gold target generations for src_valid.txt, respectively. I've updated data/make_e2e_labedata.py to make that clear.
