### ISSUE TITLE
src_train.txt, src_valid.txt and src_uniq_valid.txt of WikiBio is missing in wb_aligned.tar.gz

### ISSUE THREAD

**Issue by felixgwu** [harvardnlp/neural-template-gen#3]
Hi authors,

Thank you sharing the code of this awesome work.
I untarred the  _wb_aligned.tar.gz_  and found that _src_train.txt,_ _src_valid.txt_ and _src_uniq_valid.txt_ are missing.
Therefore, I couldn't trained the model on WikiBio. 
Could you please share the files or the command that generates these files?

Thanks in advance.

Best,
Felix

**Comment by wanghechong** [comment]
when he train the model, he directly use the original data, do not  preprocess the data, you just need correct some code in the script,  if what i understand is not wrong!

**Comment by swiseman** [comment]
Hi Felix,

Right, as @wanghechong mentions, the code assumes the WikiBio src files are in the same format as in the original wikibio data. So you can just download the WikiBio data from the link in the README and then extract src databases (for train, valid, and test) as in lines 126-137 of [data/make_wikibio_labedata.py](https://github.com/harvardnlp/neural-template-gen/blob/master/data/make_wikibio_labedata.py); see issue #1.

Regarding src_uniq_valid.txt, that's only necessary for the E2E data, where the validation src databases are repeated for each reference text; in WikiBio there is only one reference per database, and so src_valid is already unique.
