### ISSUE TITLE
TypeError occurred when generation

### ISSUE THREAD

**Issue by liqiangniu** [harvardnlp/neural-template-gen#5]
hi, there
After model training and segment, runtime error occurred! 
pytorch_py27/lib/python2.7/site-packages/torch/nn/functional.py:995: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")
chsmm.py:505: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  inps = Variable(torch.LongTensor(K, 4), volatile=True)
Traceback (most recent call last):
  File "chsmm.py", line 1376, in <module>
    gen_from_src()
  File "chsmm.py", line 1297, in gen_from_src
    gen_from_srctbl(src_tbl, top_temps, coeffs, src_line=src_line)
  File "chsmm.py", line 1207, in gen_from_srctbl
    srcfieldenc, len_lps, row2tblent, row2feats)
  File "chsmm.py", line 600, in gen_one
    args.beamsz, final_state=(stidx == len(templt)-1))
  File "chsmm.py", line 535, in temp_bs
    wlenscore = maxprobs[k]/(ell+1) + len_lps[ss][ell-1]
RuntimeError: Expected object of type torch.FloatTensor but found type torch.cuda.FloatTensor for argument #3 'other'

**Comment by swiseman** [comment]
This looks like a pytorch version issue. The code only supports pytorch 0.3; see #2.

**Comment by liqiangniu** [comment]
Solved！pytorch 0.3 is ok~ thanks~
