### ISSUE TITLE
question about backward algorithm initialization

### ISSUE THREAD

**Issue by sizhen** [harvardnlp/neural-template-gen#7]
https://github.com/harvardnlp/neural-template-gen/blob/9511e52444f58f4827b02b95dee35139909f2c75/infc.py#L170

In the paper, Section 5.2 said 

> We have with base case beta[seqlen] (j) = 1.

why set 0 in code?

**Comment by swiseman** [comment]
We run the dynamic programs in "log space" for numerical stability. That is, we calculate log probabilities (rather than probabilities), replacing multiplication with addition and addition with log-sum-exp.
