### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by vedikaparvez** [harvardnlp/neural-template-gen#9]
Hello,

I came across your paper recently, and found your work very informative and interesting. Further, I tried recreating the model by training it on AWS, but encountered 'CUDA out of memory error' during the validation step of e2e_aligned data set on an NVIDIA K80. The first epoch completed training successfully, but the script crashes on the validation step.

It would be great if you could share the exact hardware config you used to train the model.

**Comment by swiseman** [comment]
Hello,

We trained with a Maxwell-era Titan X. If you're running out of memory during validation, it should be relatively simple to decrease the validation batch size [here](https://github.com/harvardnlp/neural-template-gen/blob/master/labeled_data.py#L81), by using a different batch size than the one used in training.
